#!/usr/bin/env bash

set -ex

sudo apt install -y podman-remote
sudo apt install -y stow
sudo apt install -y btop
sudo apt install -y eza
sudo apt install -y fzf
sudo apt install -y ripgrep

mkdir -p ~/.config
mkdir -p ~/.local/bin
mkdir -p ~/.local/share

stow --adopt . && git checkout .

git clone --filter=blob:none --branch=stable https://github.com/folke/lazy.nvim.git ~/.local/share/nvim/lazy/lazy.nvim

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
. ~/.nvm/nvm.sh

sudo apt install -y fish
curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | argv=--noninteractive fish --no-config

nvim --headless "+Lazy! sync" +qa
nvm install --lts

podman system connection add host unix:///run/user/1000/podman/podman.sock
