#!/usr/bin/env bash

set -ex

brew install podman
brew install stow
brew install btop
brew install eza
brew install fzf
brew install ripgrep
brew install neovim

mkdir -p ~/.config
mkdir -p ~/.local/bin
mkdir -p ~/.local/share

stow --adopt . && git checkout .

git clone --filter=blob:none --branch=stable https://github.com/folke/lazy.nvim.git ~/.local/share/nvim/lazy/lazy.nvim

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
. ~/.nvm/nvm.sh

brew install fish
curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | argv=--noninteractive fish --no-config

nvim --headless "+Lazy! sync" +qa
nvm install --lts
